apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-app
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: syslog-{{ lower (.Values.service.protocol) }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}-app
  type: {{ .Values.service.type }}